project:
  type: website
  output-dir: _site
  preview:
    port: 4201
    browser: false
  render:
    - index.qmd
    - chapters/chapter1/survol.qmd
    - chapters/chapter1/comparaison_GB_RF.qmd
    - chapters/chapter2/CART.qmd
    - chapters/chapter2/bagging.qmd
    - chapters/chapter2/random_forest.qmd
    - chapters/chapter2/boosting.qmd
    - chapters/chapter3/guide_usage_RF.qmd
  resources: 
    - "*.svg"
  post-render: 
    ./render_pdf_output.sh


website: 
  page-navigation: true
  title: "Introduction aux méthodes ensemblistes"
  site-url: "https://github.com/oliviermeslin/DT_methodes_ensemblistes" 
  repo-url: "https://github.com/oliviermeslin/DT_methodes_ensemblistes"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Survol des méthodes ensemblistes"
        href: chapters/chapter1/survol.qmd
        contents:
          - chapters/chapter1/survol.qmd
          - chapters/chapter1/comparaison_GB_RF.qmd
      - section: "Présentation formelle des algorithmes"
        href: chapters/chapter2/CART.qmd
        contents:
          - chapters/chapter2/CART.qmd
          - chapters/chapter2/bagging.qmd
          - chapters/chapter2/random_forest.qmd
          - chapters/chapter2/boosting.qmd
      - section: "Comment bien utiliser les algorithmes?"
        href: chapters/chapter3/guide_usage_RF.qmd
        contents:
          - chapters/chapter3/guide_usage_RF.qmd
    background: "#D9E3E4"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nmfs-opensci.github.io
        text: "NMFS Open Science"
      - icon: github
        href: https://github.com/nmfs-opensci
        text: "NMFS OpenSci"

format:
  html: 
    theme: litera
    code-copy: true
    code-overflow: wrap
    toc: true
bibliography: references.bib
