project:
  type: website
  output-dir: _site
  preview:
    port: 4201
    browser: false
  render:
    - index.qmd
    - chapters/chapter1/1-survol.qmd
    - chapters/chapter1/2-comparaison_GB_RF.qmd
    - chapters/chapter2/1-CART.qmd
    - chapters/chapter2/2-bagging.qmd
    - chapters/chapter2/3-random_forest.qmd
    - chapters/chapter2/4-boosting.qmd
    - chapters/chapter2/ajouts_boosting.qmd
    - chapters/chapter3/1-preparation_donnees.qmd
    - chapters/chapter3/2-guide_usage_RF.qmd
    - chapters/chapter3/3-guide_usage_GB.qmd
    - pdf/dt_methodes_ensemblistes.qmd
  resources: 
    - "*.svg"

author:
  - name: Mélina Hillion
    url: https://github.com/melinahillion
    email: melina.hillion@insee.fr
  - name: Olivier Meslin
    url: https://github.com/oliviermeslin
    email: olivier.meslin@insee.fr

website: 
  page-navigation: true
  title: "Introduction aux méthodes ensemblistes"
  site-url: "https://github.com/inseefrlab/DT_methodes_ensemblistes" 
  repo-url: "https://github.com/inseefrlab/DT_methodes_ensemblistes"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Survol des méthodes ensemblistes"
        href: chapters/chapter1/1-survol.qmd
        contents:
          - chapters/chapter1/1-survol.qmd
          - chapters/chapter1/2-comparaison_GB_RF.qmd
      - section: "Présentation formelle des algorithmes"
        href: chapters/chapter2/1-CART.qmd
        contents:
          - chapters/chapter2/1-CART.qmd
          - chapters/chapter2/2-bagging.qmd
          - chapters/chapter2/3-random_forest.qmd
          - chapters/chapter2/4-boosting.qmd
          - chapters/chapter2/ajouts_boosting.qmd
      - section: "Comment bien utiliser les algorithmes?"
        href: chapters/chapter3/1-preparation_donnees.qmd
        contents:
          - chapters/chapter3/1-preparation_donnees.qmd
          - chapters/chapter3/2-guide_usage_RF.qmd
          - chapters/chapter3/3-guide_usage_GB.qmd
    background: "#D9E3E4"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: file-pdf-fill
        href: ./pdf/dt_methodes_ensemblistes.pdf
        text: "NMFS Open Science"

format:
  html:
    css: custom.css
    theme: 
      - litera
    code-copy: true
    code-overflow: wrap
    toc: true
    number-sections: true    # Pour la numérotation des sections
    fig_caption: true        # Pour la numérotation des figures
    crossref:
      fig-prefix: ""
      tbl-prefix: ""
      eq-prefix: ""
#   typst:
#     keep-typ: true
#     template: _extensions/quarto-ext/ams/template.typ
#     template-partials:
#       - _extensions/quarto-ext/ams/typst-template.typ
#       - _extensions/quarto-ext/ams/typst-show.typ
#       - customisation_template.typ
#     toc: true
#     section-numbering: 1.1.1
# format-links: false

bibliography: references.bib
