project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: false
  render:
    - index.qmd

title: "Introduction aux méthodes ensemblistes"
subtitle: "On va vous booster le gradient"
author: |
  [Olivier Meslin](https://github.com/oliviermeslin)
  [Mélina Hillion](https://github.com/melinahillion)

website: 
  page-navigation: true
  title: "Introduction aux méthodes ensemblistes"
  site-url: "https://github.com/oliviermeslin/DT_methodes_ensemblistes" 
  repo-url: "https://github.com/oliviermeslin/DT_methodes_ensemblistes"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nmfs-opensci.github.io
        text: "NMFS Open Science"
      - icon: github
        href: https://github.com/nmfs-opensci
        text: "NMFS OpenSci"

format:
  html: 
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true
  # typst:
  #   output-file: dt_methodes_ensemblistes.pdf
  #   keep-typ: true
  #   template: _extensions/quarto-ext/ams/template.typ
  #   template-partials:
  #     - _extensions/quarto-ext/ams/typst-template.typ
  #     - _extensions/quarto-ext/ams/typst-show.typ
  #     - customisation_template.typ
  #   toc: true
  #   section-numbering: 1.1.1
bibliography: references.bib
