project:
  type: website
  render:
    - index.qmd

title: "Introduction aux méthodes ensemblistes"
subtitle: "Plan détaillé"
author: |
  [Olivier Meslin](https://github.com/oliviermeslin)
  [Mélina Hillion](https://github.com/melinahillion)
format:
  typst:
    output-file: dt_methodes_ensemblistes.pdf
    template: _extensions/quarto-ext/ams/template.typ
    template-partials:
      - _extensions/quarto-ext/ams/typst-template.typ
      - _extensions/quarto-ext/ams/typst-show.typ
    toc: true
    section-numbering: 1.1.1
bibliography: references.bib
