
---
title: "Introduction aux méthodes ensemblistes"
author:
  - name: Mélina Hillion
    url: https://github.com/melinahillion
    email: melina.hillion@insee.fr
  - name: Olivier Meslin
    url: https://github.com/oliviermeslin
    email: olivier.meslin@insee.fr
---



# Introduction

::: {.content-visible when-format="html"}

La version pdf de ce document est disponible [ici](https://inseefrlab.github.io/DT_methodes_ensemblistes/pdf/dt_methodes_ensemblistes.pdf).

:::

Deux constats:

- Puissance prédictive, diversité des cas d'usage, pertinence pour les travaux de la statistique publique.

- Pourtant, méthodes peu connues et peu utilisées dans la statistique publique, probablement en raison de l'éclatement des ressources consacrées aux méthodes ensemblistes: articles fondateurs parfois difficiles à lire, nombreux tutoriels souvent peu développés. 

Ce document répond à plusieurs ambitions:

- __Proposer deux niveaux de lecture__: un premier niveau qui s'adresse à ceux qui souhaitent comprendre la logique des méthodes ensembliste sans se plonger dans les détails techniques, et un second niveau qui entre davantage dans les détails des algorithmes et de leurs implémentations. L'existence de ces deux niveaux de lecture implique nécessairement quelques répétitions, qu'on espère toutefois peu nombreuses.

- __Proposer une introduction raisonnée aux méthodes ensemblistes qui rassemble l'ensemble des connaissances pertinentes__: fondements théoriques et propriétés des algorithmes, description des implémentations existantes et guide d'usage détaillé.

Détailler le plan

- La première partie propose une vue d'ensemble des méthodes ensemblistes
