name: Build PDF with Quarto and Typst

on:
  push:
    branches:
      - main  # Triggers workflow on push to the main branch

jobs:
  if: "!contains(github.event.commits[0].message, '[skip ci]')"
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Quarto
      - name: Install Quarto
        run: |
          wget https://quarto.org/download/latest/quarto-linux-amd64.deb
          sudo dpkg -i quarto-linux-amd64.deb

      # Step 3: Compile document with Quarto
      - name: Build PDF with Quarto
        run: |
          quarto render boosting.qmd

      # Step 4: Upload the PDF as a GitHub Actions artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-pdf
          path: |
            boosting.pdf    # Typst/PDF output
