name: Build the website and the pdf output

on:
  push:
    branches:
      - main  # Triggers workflow on push to the main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Quarto
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Step 3: Compile document
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
